### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by Hexorg** [Hexorg/bevy_copperfield#4]
chess example throws 
```
thread '<unnamed>' panicked at src\mesh\attributes.rs:235:46:
called `Option::unwrap()` on a `None` value
```

simple_ops:
```
thread 'Compute Task Pool (23)' panicked at src\mesh\face_ops.rs:39:9:
Vertices HalfEdgeId(32v1) and VertexId(10v1) provided to split a face already share an edge
```

stick:
```
2024-11-16T04:17:34.196422Z  INFO bevy_winit::system: Creating new window "App" (Entity { index: 0, generation: 1 })
Face count: 5252
thread 'Compute Task Pool (23)' panicked at src\mesh\attributes.rs:192:14:
Vertices don't have UV attribute.
```

**Comment by Hexorg** [comment]
Fixed in 7187b0d5141b03fdf19c2ecdf704120c9e48c214
